/**
 * Fetches true-colour cover art from official, no-key sources and pre-bakes
 * optimised assets so the Vite build stays free of native deps.
 *
 *   AniList (anime + anime films) · Steam CDN (games)
 *
 * The collection itself is the work list — this script only knows WHERE each
 * work's art comes from. For each work it writes:
 *   src/assets/works/<slug>.webp        — optimised cover (≤640w)
 *   src/data/generated/covers.ts        — { placeholder, w, h, source }
 *
 * Run:  LD_LIBRARY_PATH=<gcc-lib> bun scripts/fetch-covers.ts
 * (libvips/sharp needs libstdc++ on PATH; the nix dev shell provides it.)
 */
import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import sharp from "sharp";
import { rgbaToThumbHash, thumbHashToDataURL } from "thumbhash";
import { allWorks } from "../src/data/works";
import { SOURCES } from "./cover-sources";

const ROOT = resolve(import.meta.dirname, "..");
const ASSETS = resolve(ROOT, "src/assets/works");
const GEN = resolve(ROOT, "src/data/generated");

interface CoverMeta {
  slug: string;
  width: number;
  height: number;
  placeholder: string;
  credit: string;
  sourceUrl: string;
}

/** What a source hands back before the image is processed. */
interface Fetched {
  url: string;
  credit: string;
  sourceUrl: string;
}

async function anilist(search: string): Promise<Fetched> {
  const query = `query($s:String){Media(search:$s,type:ANIME){coverImage{extraLarge} siteUrl}}`;
  const res = await fetch("https://graphql.anilist.co", {
    method: "POST",
    headers: { "Content-Type": "application/json", Accept: "application/json" },
    body: JSON.stringify({ query, variables: { s: search } }),
  });
  if (!res.ok) throw new Error(`AniList ${res.status}`);
  const json = (await res.json()) as {
    data?: {
      Media?: {
        coverImage?: { extraLarge?: string };
        siteUrl?: string;
      };
    };
  };
  const m = json.data?.Media;
  if (!m?.coverImage?.extraLarge) throw new Error("no cover");
  return {
    url: m.coverImage.extraLarge,
    credit: "AniList",
    sourceUrl: m.siteUrl ?? "https://anilist.co",
  };
}

function steam(appid: number): Fetched {
  return {
    url: `https://cdn.cloudflare.steamstatic.com/steam/apps/${appid}/library_600x900_2x.jpg`,
    credit: "Steam",
    sourceUrl: `https://store.steampowered.com/app/${appid}/`,
  };
}

async function download(url: string) {
  const res = await fetch(url, {
    headers: {
      "User-Agent": "perfect-collection/1.0 (personal, non-commercial)",
    },
  });
  if (!res.ok) throw new Error(`download ${res.status}`);
  return Buffer.from(await res.arrayBuffer());
}

async function process(slug: string, meta: Fetched): Promise<CoverMeta> {
  const raw = await download(meta.url);
  const dest = resolve(ASSETS, `${slug}.webp`);
  const out = sharp(raw).resize({ width: 640, withoutEnlargement: true });
  const { width = 0, height = 0 } = await out
    .clone()
    .webp({ quality: 82 })
    .toFile(dest)
    .then(() => out.metadata());

  // The blurred stand-in, baked as a data URL rather than as thumbhash bytes:
  // the page paints it directly, so the decoder never has to ship to a reader.
  const small = await sharp(raw)
    .resize(90, 90, { fit: "inside" })
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });
  const placeholder = thumbHashToDataURL(
    rgbaToThumbHash(small.info.width, small.info.height, small.data),
  );

  const m = await sharp(dest).metadata();
  return {
    slug,
    width: m.width ?? width,
    height: m.height ?? height,
    placeholder,
    credit: meta.credit,
    sourceUrl: meta.sourceUrl,
  };
}

/** The generated module: cover data only. Anything derived from it — the
 *  by-slug index, the asset URLs — is built in src/lib/covers.ts. */
function emit(covers: readonly CoverMeta[]): Promise<void> {
  const body = `// GENERATED by scripts/fetch-covers.ts — do not edit by hand.
export interface CoverMeta {
  slug: string;
  width: number;
  height: number;
  placeholder: string;
  credit: string;
  sourceUrl: string;
}

export const covers = ${JSON.stringify(covers, null, 2)} as const satisfies readonly CoverMeta[];
`;
  return writeFile(resolve(GEN, "covers.ts"), body);
}

async function main() {
  await mkdir(ASSETS, { recursive: true });
  await mkdir(GEN, { recursive: true });

  const covers: CoverMeta[] = [];
  let sourced = 0;
  for (const { work } of allWorks) {
    const source = SOURCES[work.slug];
    if (!source) {
      console.log(`· ${work.slug}  no licensed source — typographic panel`);
      continue;
    }
    sourced++;
    try {
      const meta =
        source.kind === "anilist"
          ? await anilist(source.search)
          : steam(source.appid);
      const cover = await process(work.slug, meta);
      covers.push(cover);
      console.log(
        `✓ ${work.slug}  ${cover.width}x${cover.height}  (${cover.credit})`,
      );
      if (source.kind === "anilist")
        await new Promise((r) => setTimeout(r, 800)); // rate-limit
    } catch (e) {
      console.warn(`✗ ${work.slug}: ${(e as Error).message}`);
    }
  }

  await emit(covers);
  console.log(
    `\nWrote ${covers.length}/${sourced} covers → src/data/generated/covers.ts`,
  );
}

await main();
